### ISSUE TITLE
Question about the package used for runnning the code.

### ISSUE THREAD

**Issue by xiangyh9988** [zzs1324/BO-DBA#1]
https://github.com/zzs1324/BO-DBA/blob/2f4496fd50a0614d1d9cdbf2882c819acc64657c/AdversarialAttack.py#L205
Hi, thanks for your interesting work. When I try to run the demo.ipynb, there is a `ModuleNotFoundError`, i.e., `No module named 'Upsample'`, which corresponds to #L205 referenced above. 
I think it is a package your implemented to perform upsampling operations, right? Maybe I can reimplement one that can upsample the perturbation. However, I'm not quite clear about the detailed procedure in your `upsample_projection` function, so it might cause wrong results if I just simply write a upsampling function. So, could you please provide your `Upsample.py`? Thanks!

**Comment by zzs1324** [comment]
uploaded
